/*Given a string, we have to find out all subsequences of it. A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.

Examples:

Input : abc
Output : a, b, c, ab, bc, , abc

Input : aaa
Output : a, a, a, aa, aa, , aaa
*/
#include <bits/stdc++.h>
using namespace std;
int main()
{
    string s = "abc";
    for (int i = 0; i < s.size(); i++)
    {
        string ans = "";
        for (int j = i; j < s.size(); j++)
        {

            ans = ans + s[j];
            cout << ans << endl;
        }
    }
    return 0;
}